[project]
name = "mypthon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "koreanize-matplotlib>=0.1.1",
    "matplotlib>=3.11.1",
    "openai>=2.53.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.2",
    "seaborn>=0.13.2",
    "setuptools>=83.0.0",
    "streamlit>=1.61.1",
]

[project.scripts]
mypthon = "mypthon:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
